//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_StPats
    {
        public long id_bill { get; set; }
        public System.DateTime date { get; set; }
        public int id_paymet { get; set; }
        public long id_shoppingCart { get; set; }
        public int id_estado { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual PayMet_StPats PayMet_StPats { get; set; }
        public virtual Shopping_Cart_StPats Shopping_Cart_StPats { get; set; }
    }
}
