//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_StPats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients_StPats()
        {
            this.Shopping_Cart_StPats = new HashSet<Shopping_Cart_StPats>();
        }
    
        public int id_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string retry_password { get; set; }
        public int id_ciudad_estado { get; set; }
        public string zip_code { get; set; }
        public string telefono { get; set; }
        public int estado { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual StaCi_StPats StaCi_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_Cart_StPats> Shopping_Cart_StPats { get; set; }
    }
}
