//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtros_StPats
    {
        public int id_filtro { get; set; }
        public string filtro_codigo { get; set; }
        public string numero_plates { get; set; }
        public float area_superficie { get; set; }
        public decimal precio { get; set; }
    }
}
