//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter_CH_StPats
    {
        public int id_filter_ch { get; set; }
        public int id_producto_general { get; set; }
        public int id_tipo_product { get; set; }
        public string code_produt { get; set; }
        public string name_product { get; set; }
        public string description { get; set; }
        public int id_location { get; set; }
        public int id_manufactured { get; set; }
        public int stock { get; set; }
        public int id_estado { get; set; }
        public string extra_things { get; set; }
        public float micron { get; set; }
        public decimal price_single_10 { get; set; }
        public decimal price_single_30 { get; set; }
        public decimal price_triple_30 { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual Locations_StPats Locations_StPats { get; set; }
        public virtual Manufactured_Stpats Manufactured_Stpats { get; set; }
        public virtual Productos_StPats Productos_StPats { get; set; }
        public virtual Tipo_Producto_StPats Tipo_Producto_StPats { get; set; }
    }
}
