//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labeler_StPats
    {
        public int id_labeler { get; set; }
        public int id_producto_general { get; set; }
        public int id_tipo_product { get; set; }
        public string code_produt { get; set; }
        public string name_product { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public Nullable<int> voltage_regulator { get; set; }
        public int id_location { get; set; }
        public string image { get; set; }
        public string manual { get; set; }
        public int id_manufactured { get; set; }
        public int estado { get; set; }
        public int stock { get; set; }
        public string extra_things { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual Labeler_StPats Labeler_StPats1 { get; set; }
        public virtual Labeler_StPats Labeler_StPats2 { get; set; }
        public virtual Locations_StPats Locations_StPats { get; set; }
        public virtual Manufactured_Stpats Manufactured_Stpats { get; set; }
        public virtual Productos_StPats Productos_StPats { get; set; }
        public virtual Tipo_Producto_StPats Tipo_Producto_StPats { get; set; }
    }
}
