//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_Productos_StPats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lista_Productos_StPats()
        {
            this.Shopping_Cart_Detalle_StPats = new HashSet<Shopping_Cart_Detalle_StPats>();
        }
    
        public long id_lista_producto { get; set; }
        public int id_producto { get; set; }
        public int id_cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal precio_total { get; set; }
        public int id_estado { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual Productos_StPats Productos_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_Cart_Detalle_StPats> Shopping_Cart_Detalle_StPats { get; set; }
    }
}
