//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufactured_Stpats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manufactured_Stpats()
        {
            this.Bottle_Finishing_StPats = new HashSet<Bottle_Finishing_StPats>();
            this.Filling_Machine_StPats = new HashSet<Filling_Machine_StPats>();
            this.Labeler_StPats = new HashSet<Labeler_StPats>();
        }
    
        public int id_manufactured { get; set; }
        public string name_manufactured { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bottle_Finishing_StPats> Bottle_Finishing_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filling_Machine_StPats> Filling_Machine_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Labeler_StPats> Labeler_StPats { get; set; }
    }
}
