//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_StPats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos_StPats()
        {
            this.Bottle_Finishing_StPats = new HashSet<Bottle_Finishing_StPats>();
            this.Filling_Machine_StPats = new HashSet<Filling_Machine_StPats>();
            this.Labeler_StPats = new HashSet<Labeler_StPats>();
            this.Lista_Productos_StPats = new HashSet<Lista_Productos_StPats>();
            this.Pump_StPats = new HashSet<Pump_StPats>();
        }
    
        public int id_producto { get; set; }
        public int id_tipo_producto { get; set; }
        public string codigo { get; set; }
        public decimal price { get; set; }
        public int stock { get; set; }
        public string description { get; set; }
        public int id_location { get; set; }
        public string image { get; set; }
        public int id_estado { get; set; }
        public string manual { get; set; }
        public int stock_menos_carrito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bottle_Finishing_StPats> Bottle_Finishing_StPats { get; set; }
        public virtual Estado_StPats Estado_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filling_Machine_StPats> Filling_Machine_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Labeler_StPats> Labeler_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lista_Productos_StPats> Lista_Productos_StPats { get; set; }
        public virtual Locations_StPats Locations_StPats { get; set; }
        public virtual Tipo_Producto_StPats Tipo_Producto_StPats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pump_StPats> Pump_StPats { get; set; }
    }
}
