//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart_Detalle_StPats
    {
        public long id_shoppingcart_detalle { get; set; }
        public long id_shoppingcart { get; set; }
        public long id_lista_producto { get; set; }
        public int id_estado { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual Lista_Productos_StPats Lista_Productos_StPats { get; set; }
        public virtual Shopping_Cart_StPats Shopping_Cart_StPats { get; set; }
    }
}
