//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statax_StPats
    {
        public int id_estado_impuesto { get; set; }
        public int id_estado { get; set; }
        public float impuesto { get; set; }
    
        public virtual State_StPats State_StPats { get; set; }
    }
}
