//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank_LWWFWCJCT_VC_StPats
    {
        public int id_filter_acf { get; set; }
        public int id_producto_general { get; set; }
        public int id_tipo_product { get; set; }
        public string code_produt { get; set; }
        public string name_product { get; set; }
        public string description { get; set; }
        public int id_location { get; set; }
        public int id_manufactured { get; set; }
        public int stock { get; set; }
        public int id_estado { get; set; }
        public string extra_things { get; set; }
        public string capacity { get; set; }
        public string orientation { get; set; }
        public float total_area { get; set; }
        public string botton_valve { get; set; }
        public string manway { get; set; }
        public int vent { get; set; }
        public string ladder_support { get; set; }
        public string sample_tap { get; set; }
        public string thermometer_in_thermowell { get; set; }
        public string thermowell_for_sensor { get; set; }
        public string level_gange { get; set; }
        public string top_hatch { get; set; }
        public string wall_thickness_bottom_thickness { get; set; }
        public decimal price { get; set; }
    
        public virtual Estado_StPats Estado_StPats { get; set; }
        public virtual Locations_StPats Locations_StPats { get; set; }
        public virtual Manufactured_Stpats Manufactured_Stpats { get; set; }
        public virtual Productos_StPats Productos_StPats { get; set; }
        public virtual Tipo_Producto_StPats Tipo_Producto_StPats { get; set; }
    }
}
