//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanks_StPats
    {
        public int id_tanque { get; set; }
        public string codigo_tanque { get; set; }
        public string capacidad { get; set; }
        public float bottom_valve { get; set; }
        public int manway { get; set; }
        public int lifting_arm { get; set; }
        public int vent { get; set; }
        public string replacemnet_infiatable_gasket { get; set; }
        public decimal price { get; set; }
        public int stok { get; set; }
        public int location { get; set; }
        public string manual { get; set; }
        public string image { get; set; }
        public string desription { get; set; }
    
        public virtual Locations_StPats Locations_StPats { get; set; }
    }
}
